### PR TITLE
gha: add concurrent test

### PR DESCRIPTION
**Pull request by Desiki-high**
# Add concurrent test for converting images.
- Test the same image conversion tasks in high concurrent.
- Test the different image conversion tasks in high concurrent.

Ref: #174

### CODE REVIEW

**Comment by Desiki-high** [comment]
Please don't merge until other pr fix the error in concurrent.

**Comment by imeoer** [comment]
It seems still have a concurrent race issue after merging https://github.com/goharbor/acceleration-service/pull/172.

**Comment by Desiki-high** [comment]
> It seems still have a concurrent race issue in this test after merging #172 and retired the test.

Yes, gc still clears blobs which will be used by converting tasks, I will try other ways to fix it. Keep this pr unmerged.

**Comment by Desiki-high** [comment]
Since https://github.com/goharbor/acceleration-service/pull/175 was merged，this pr works well now.

**Review by imeoer — APPROVED** [review]
LGTM! Thanks for the test script.

**Pull request merged**
